name: Update Image List

on:
  push:
    paths:
      - 'tuatahi-tuari/images/**'  # Trigger when anything in the images folder changes

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Generate image-list.json (handles spaces in filenames)
      run: |
        IMAGE_DIR="tuatahi-tuari/images"
        JSON_FILE="tuatahi-tuari/image-list.json"

        # Start JSON file
        echo "{" > "$JSON_FILE"
        echo '  "images": [' >> "$JSON_FILE"

        # Read filenames safely (handles spaces)
        find "$IMAGE_DIR" -type f \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" -o -iname "*.gif" \) -print0 |
        while IFS= read -r -d '' IMAGE; do
          REL_PATH="${IMAGE#$IMAGE_DIR/}"
          echo "    \"${REL_PATH}\"," >> "$JSON_FILE"
        done

        # Remove trailing comma and close JSON
        sed -i '$ s/,$//' "$JSON_FILE"
        echo "  ]" >> "$JSON_FILE"
        echo "}" >> "$JSON_FILE"

    - name: Commit and push changes
      uses: EndBug/add-and-commit@v7
      with:
        author_name: 'GitHub Actions'
        author_email: 'actions@github.com'
        message: 'docs: update image-list.json'
        add: 'tuatahi-tuari/image-list.json'
