name: Update Media List

on:
  push:
    paths:
      - 'tuatahi-tuari/images/**'

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install curl & jq
      run: sudo apt-get install -y jq curl

    - name: Generate image-list.json with images and Cloudinary videos
      env:
        CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
        API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
        API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
      run: |
        IMAGE_DIR="tuatahi-tuari/images"
        JSON_FILE="tuatahi-tuari/image-list.json"
        TEMP_FILE=$(mktemp)

        echo '{ "media": [' > "$TEMP_FILE"

        # Add images
        find "$IMAGE_DIR" -type f \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" -o -iname "*.gif" \) -print0 |
        while IFS= read -r -d '' IMAGE; do
          REL_PATH="${IMAGE#$IMAGE_DIR/}"
          echo "    {\"type\": \"image\", \"src\": \"${REL_PATH}\"}," >> "$TEMP_FILE"
        done

        # Add Cloudinary videos
        VIDEO_RESPONSE=$(curl -s -u "$API_KEY:$API_SECRET" "https://${API_KEY}:${API_SECRET}@api.cloudinary.com/v1_1/$CLOUD_NAME/resources/video/upload?prefix=nan-videos/&max_results=100")

        echo "$VIDEO_RESPONSE" | jq -r '.resources[] | "    {\"type\": \"video\", \"src\": \"" + .secure_url + "\"},"' >> "$TEMP_FILE"

        # Remove trailing comma
        sed -i '$ s/,$//' "$TEMP_FILE"

        echo '] }' >> "$TEMP_FILE"

        # Move to final JSON file
        mv "$TEMP_FILE" "$JSON_FILE"

    - name: Commit and push changes
      uses: EndBug/add-and-commit@v7
      with:
        author_name: 'GitHub Actions'
        author_email: 'actions@github.com'
        message: 'docs: update image-list.json with images and videos'
        add: 'tuatahi-tuari/image-list.json'
