name: Update Image List

on:
  push:
    paths:
      - 'tuatahi-tuari/images/**'  # Trigger when images are added/removed/changed

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Generate image-list.json
      run: |
        IMAGE_DIR="tuatahi-tuari/images"
        JSON_FILE="tuatahi-tuari/image-list.json"

        # Find image files and remove the path prefix for JSON
        IMAGE_FILES=$(find "$IMAGE_DIR" -type f \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" -o -iname "*.gif" \) | sed "s|$IMAGE_DIR/||")

        # Generate the JSON structure
        echo "{
          \"images\": [" > "$JSON_FILE"

        for IMAGE in $IMAGE_FILES; do
          echo "  \"$IMAGE\"," >> "$JSON_FILE"
        done

        # Remove trailing comma and close JSON
        sed -i '$ s/,$//' "$JSON_FILE"
        echo "]}" >> "$JSON_FILE"

    - name: Commit and push changes
      uses: EndBug/add-and-commit@v7
      with:
        author_name: 'GitHub Actions'
        author_email: 'actions@github.com'
        message: 'Update image-list.json'
        add: 'tuatahi-tuari/image-list.json'
